---

language: python
python: "2.7"

branches:
  only:
    - develop
    - master

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==2.1
  # Install Test Kitchen
  - gem install test-kitchen
  - gem install kitchen-ansible
  - gem install kitchen-docker


script:
  # Run Test
  - kitchen test
