---

- name: Install
  include: install.yml
  tags:
    - install

- name: Configure
  include: configure.yml
  tags:
    - configure

- name: Configure S3 Sync
  include: s3-sync.yml
  tags:
    - configure

- name: Ensure for HiveMQ is started
  wait_for:
    host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
    port: "{{ hivemq_port }}"
    state: started
