---

# In order to get all custom configs we need to download extra files
- name: Clean up standard configs and plugins
  file:
    name: "{{ hivemq_dir }}/{{ item }}"
    state: absent
  with_items: "{{ hivemq_config_dirs }}"
  when: configs_from_s3 and hivemq_config_refresh


- name: Sync S3 config
  command: "aws s3 sync s3://{{ hivemq_config_bucket }}/{{ hivemq_object_prefix }}/{{ item }} {{ hivemq_dir }}/{{ item }}/"
  args:
    creates: "{{ hivemq_dir }}/{{ item }}/"
  with_items: "{{ hivemq_config_dirs }}"
  when: "{{ hivemq_config_refresh }}"
  notify: restart hivemq

- name: S3 Permissions
  file:
    name: "{{ hivemq_dir }}/{{ item }}"
    state: directory
    owner: "{{ hivemq_user }}"
    group: "{{ hivemq_group }}"
    recurse: yes
  with_items: "{{ hivemq_config_dirs }}"
  when: "{{ configs_from_s3 }}"

#- name: Get s3_bucket_items
#  s3:
#    mode: list
#    bucket: "{{ hivemq_config_bucket }}"
#    prefix: "{{ hivemq_object_prefix}}/{{ item }}/"
#    region: "{{ hivemq_aws_region }}"
#  with_items: "{{ hivemq_config_dirs }}"
#  register: s3_bucket_items
#
#
#- name: Set flat items
#  set_fact:
#    s3_items: "{{ item | map(attribute='item') | list}}"
#  with_items: s3_bucket_items
#
#

#- name: Download s3_bucket_items
#  s3:
#    mode: get
#    bucket: "{{ hivemq_config_bucket }}"
#    object: "{{ item }}"
#    region: "{{ hivemq_aws_region }}"
#    dest: "{{ hivemq_dir }}/{{ item }}"
#  with_items: "{{ s3_bucket_items[item][s3_keys] }}"
#  notify:
#    - restart hivemq
#- name: "Show debug"
#  debug:
#    var: s3_bucket_items

#- name: Download s3_bucket_items
#  s3:
#    mode=get
#    bucket="{{ hivemq_config_bucket }}"
#    object="{{ hivemq_object_prefix }}/{{ item }}/"
#    region="{{ hivemq_aws_region }}"
#    dest="{{ hivemq_dir }}/{{ item }}/"
#  with_items: "{{ hivemq_config_dirs }}"

#  notify:
#    - restart hivemq


#- name: Symlink configs
#  file:
#    src: "/mnt/hivemq-config/{{ item }}"
#    path: "{{ hivemq_dir}}/{{ item }}"
#    state: link
#    owner: "{{ hivemq_user }}"
#    group: "{{ hivemq_group }}"
#  with_items:
#    - conf
#    - license
#    - plugins
#    - cert
#  when: configs_from_s3
#  notify:
#    - restart hivemq
#  s3:
#    bucket: "{{ hivemq_config_bucket }}"
#    region: "{{ hivemq_aws_region }}"
#    object: "{{ hivemq_object_prefix}}"
#    aws_access_key: "{{ aws_access_key }}"
#    aws_secret_key: "{{ aws_secret_key }}"
#    dest: "{{ hivemq_dir }}/"
#    mode: get
#  notify:
#    - restart hivemq
#  when: configs_from_s3
#
