---

# In order to get all custom configs we need to download extra files
- name: Clean up standard configs and plugins
  file:
    name: "{{ hivemq_dir }}/{{ item }}"
    state: absent
  with_items: "{{ hivemq_config_dirs }}"
  when: configs_from_s3 and hivemq_config_refresh

- name: Sync S3 config
  command: "aws s3 sync s3://{{ hivemq_config_bucket }}/{{ hivemq_object_prefix }}/{{ item }} {{ hivemq_dir }}/{{ item }}/"
  args:
    creates: "{{ hivemq_dir }}/{{ item }}/"
  with_items: "{{ hivemq_config_dirs }}"
  when: configs_from_s3 and hivemq_config_refresh

- name: S3 Permissions
  file:
    name: "{{ hivemq_dir }}/{{ item }}"
    state: directory
    owner: "{{ hivemq_user }}"
    group: "{{ hivemq_group }}"
    recurse: yes
  with_items: "{{ hivemq_config_dirs }}"
  when: configs_from_s3 and hivemq_config_refresh
  notify: restart hivemq
